development:
  adapter: postgresql
  encoding: unicode
  database: provisionm_development
  pool: 5
  username: mike
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: provisionm_test
  pool: 5
  username: mike
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: provisionm_test
  pool: 5
  username: mike
  password:
